MEN-2433: Automate upload of demo application artifact in demo server
Changelog: Title

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

diff --git a/demo b/demo
--- a/demo
+++ b/demo
@@ -24,6 +24,11 @@ fi
 
 CLIENT=
 CLIENT_ARGS="-f docker-compose.client.yml -f docker-compose.client.demo.yml"
+# The demo environment has some external dependencies upon: wget, curl, jq
+hash wget 2>/dev/null || { echo >&2 "The demo script requires the 'wget' tool to be available. Aborting."; exit 1; }
+hash curl 2>/dev/null || { echo >&2 "The demo script requires the 'curl' tool to be available. Aborting."; exit 1; }
+hash jq 2>/dev/null || { echo >&2 "The demo script requires the 'jq' tool to be available. Aborting."; exit 1; }
+
 while [ -n "$1" ]; do
     if [ "$1" = "--no-client" ]; then
         echo "--no-client argument is deprecated. Client is now disabled by default and can be enabled with --client"
@@ -43,6 +48,23 @@ while [ -n "$1" ]; do
     fi
     shift
 done
+
+# Check if the demo-artifact has been downloaded,
+# or if there exists a newer one in storage.
+DEMO_ARTIFACT_NAME="mender-demo-artifact.mender"
+wget -q --timestamping https://dgsbl4vditpls.cloudfront.net/${DEMO_ARTIFACT_NAME}
+
+retval=$?
+if [ $retval -ne 0 ]; then
+    echo "Failed to download the demo artifact"
+    exit $retval
+fi
+
+if [[ "$OSTYPE" == "darwin"* ]]; then
+    ARTIFACT_SIZE_BYTES=$(stat -f %A ${DEMO_ARTIFACT_NAME}) # BSD is not GNU -_-
+else
+    ARTIFACT_SIZE_BYTES=$(stat -c %s ${DEMO_ARTIFACT_NAME})
+fi
 
 # speed up first start by pulling containers in parallel
 docker images | grep -q 'mendersoftware/deployments'
@@ -64,17 +86,169 @@ if [[ "$?" -eq 1 ]]; then
     docker-compose pull ${compose_args}
 fi
 
-if [[ "$1" == "up" ]]; then
-    echo "Starting Mender demo environment.."
-fi
-
 # Pass this value on to the GUI container as an env variable
 export INTEGRATION_VERSION=$(git describe --tags --abbrev=0)
 export MENDER_ARTIFACT_VERSION=$(extra/release_tool.py -g mender-artifact)
 
-exec docker-compose \
-     -f docker-compose.yml \
-     -f docker-compose.storage.minio.yml \
-     -f docker-compose.demo.yml \
-     $CLIENT \
-     "$@"
+RUN_UP=$(echo "$@" | grep '\bup\b')
+if [[ "$RUN_UP" == "" ]]; then
+    # exec steals the shell, so unless docker-compose is not found,
+    # exit 1 will never happen.
+    exec docker-compose \
+         -f docker-compose.yml \
+         -f docker-compose.storage.minio.yml \
+         -f docker-compose.demo.yml \
+         $CLIENT \
+         "$@"
+    exit 1
+fi
+
+# ------------------------------------------------------------------------------
+#
+#       The following code will only be run in the case ./demo up [args]
+#
+# ------------------------------------------------------------------------------
+
+# For the integration tests the name of the docker-compose project is
+# generated by pytest
+DOCKER_COMPOSE_PROJECT_NAME="${DOCKER_COMPOSE_PROJECT_NAME:-integration}"
+
+# Make sure that the demo environment is brought down on SIGINT
+exitfunc() {
+    retval=$(docker-compose \
+         -f docker-compose.yml \
+         -f docker-compose.storage.minio.yml \
+         -f docker-compose.demo.yml \
+         -p ${DOCKER_COMPOSE_PROJECT_NAME} \
+         $CLIENT \
+         stop)
+    exit $retval
+}
+
+trap exitfunc SIGINT
+
+echo "Starting the Mender demo environment..."
+
+docker-compose \
+    -f docker-compose.yml \
+    -f docker-compose.storage.minio.yml \
+    -f docker-compose.demo.yml \
+    $CLIENT \
+    "$@" -d
+
+USER='mender-demo@example.com'
+PASSWORD=$(< /dev/urandom 2>/dev/null tr -dc A-Za-z0-9 | head -c12)
+
+MENDER_SERVER_USER="${USER}:${PASSWORD}"
+MENDER_SERVER_URI="https://localhost"
+
+# Block until the useradm service returns an HTTP 4xx response
+echo "Waiting for the useradm service to start up..."
+until $USERADM_SERVICE_UP; do
+    $(curl --silent -k -X POST -u $MENDER_SERVER_USER\
+           --fail\
+           --connect-timeout 120\
+           --retry 60\
+           --retry-delay 2\
+           --retry-max-time 120\
+           $MENDER_SERVER_URI/api/management/v1/useradm/auth/login)
+    retval=$?
+    case $retval in
+        0)  USER_ADM_SERVICE_UP=true ;; # User exists - continue.
+        22) USER_ADM_SERVICE_UP=true ;; # Server 400 error, ie, server is up - continue.
+        *) echo "Failed to access the mender-useradm service"
+           echo "Please check the docker-compose setup."
+           echo "curl exit code" $retval
+           exit $retval
+           ;;
+    esac
+    sleep 2
+done
+
+
+echo "Creating a new user..."
+
+docker exec ${DOCKER_COMPOSE_PROJECT_NAME}_mender-useradm_1 /usr/bin/useradm create-user --username=${USER} --password=${PASSWORD}
+
+retval=$?
+case $retval in
+     0) echo "New user created." ;;
+     5) # Since the password is not cached in between invocations, there is no way to upload an artifact.
+        echo "The user already exists"
+        echo "Since the demo script does not cache passwords, therefore"
+        echo "run 'demo down' if you want to delete the user, and create a new demo user"
+        exit 0 ;;
+     *) exit $retval ;;
+esac
+
+echo "Getting JWT Token..."
+
+JWT=$(curl --silent -k -X POST -u $MENDER_SERVER_USER\
+        --fail\
+        --connect-timeout 120\
+        --retry 60\
+        --retry-delay 2\
+        --retry-max-time 120\
+        $MENDER_SERVER_URI/api/management/v1/useradm/auth/login)
+
+retval=$?
+if [ $retval -ne 0 ]; then
+    echo "Failed to get the 'JWT' token from the useradm service."
+    echo "This is needed in order to use the demo Artifact."
+    echo "curl exit code: " $retval
+    # exit $retval
+fi
+
+echo "JWT token: " $JWT
+
+echo "Uploading the artifact to the server..."
+cout=$(curl --silent -k -X POST \
+              --fail\
+              --show-error\
+              --connect-timeout 120\
+              --retry-delay 2\
+              --retry 60 \
+              --retry-max-time 120\
+              --header "Authorization: Bearer ${JWT}"\
+              --form "size=${ARTIFACT_SIZE_BYTES}"\
+              --form "artifact=@${DEMO_ARTIFACT_NAME}"\
+              $MENDER_SERVER_URI/api/management/v1/deployments/artifacts)
+
+retval=$?
+
+if [ $retval -ne 0 ]; then
+    echo "Failed to upload the demo Artifact to the server"
+    echo "$cout"
+    echo "curl exited with code: " $retval
+    exit $retval
+fi
+
+errout=$(jq '.error' <<< $cout)
+
+retval=$?
+
+if [ $retval -ne 0 ]; then
+    echo "Failed to parse the json response from the Mender server"
+    echo "Response: "
+    echo $cout
+    exit $retval
+fi
+
+case "$errout" in
+   " Artifact not unique"*) echo "Artifact already exists on the server" ;;
+    "") echo "Artifact uploaded to the demo server" ;;
+    *) echo "Uploading the demo artifact failed with error: " $errout
+       exit 1 ;;
+esac
+
+echo "****************************************"
+echo
+echo  "Login password: ${PASSWORD}"
+echo
+echo "****************************************"
+echo "Please keep the password available, it will not be cached by the login script."
+echo "Backend ready and running in the background. Press Enter to show the logs."
+echo "Press Ctrl-C to stop the backend and quit."
+read -se
+
+docker-compose logs --follow
