Fix the Mac issues in the demo script
Changelog: None

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

diff --git a/demo b/demo
--- a/demo
+++ b/demo
@@ -61,7 +61,7 @@ if [ $retval -ne 0 ]; then
 fi
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
-    ARTIFACT_SIZE_BYTES=$(stat -f %A ${DEMO_ARTIFACT_NAME}) # BSD is not GNU -_-
+    ARTIFACT_SIZE_BYTES=$(stat -f %z ${DEMO_ARTIFACT_NAME}) # BSD is not GNU -_-
 else
     ARTIFACT_SIZE_BYTES=$(stat -c %s ${DEMO_ARTIFACT_NAME})
 fi
@@ -136,8 +136,13 @@ docker-compose \
     $CLIENT \
     "$@" -d
 
+retval=$?
+if [[ $retval -ne 0 ]]; then
+    echo "Failed to start docker compose"
+    exit $retval
+fi
 USER='mender-demo@example.com'
-PASSWORD=$(< /dev/urandom 2>/dev/null tr -dc A-Za-z0-9 | head -c12)
+PASSWORD=$(base64 /dev/urandom | head -c 12)
 
 MENDER_SERVER_USER="${USER}:${PASSWORD}"
 MENDER_SERVER_URI="https://localhost"
@@ -149,12 +154,9 @@ echo "Waiting for the useradm service to start up..."
 RETRIES=0
 while :
 do
-    curl --silent -k -X POST -u $MENDER_SERVER_USER\
+    curl --silent -k -X POST -u ${USER}:${PASSWORD} \
          --fail\
-         --connect-timeout 120\
-         --retry 60\
-         --retry-delay 2\
-         --retry-max-time 120\
+         --connect-timeout 5\
          $MENDER_SERVER_URI/api/management/v1/useradm/auth/login
     retval=$?
     case $retval in
@@ -201,17 +203,14 @@ done
 echo "Getting JWT Token..."
 RETRIES=0
 until [[ "$JWT" != "" ]]; do
-    JWT=$(curl --silent -k -X POST -u $MENDER_SERVER_USER\
+    JWT=$(curl --silent -k -X POST -u ${USER}:${PASSWORD}\
         --fail\
-        --connect-timeout 120\
-        --retry 60\
-        --retry-delay 2\
-        --retry-max-time 120\
+        --connect-timeout 5\
         $MENDER_SERVER_URI/api/management/v1/useradm/auth/login)
     retval=$?
     if [[ $retval -ne 0 ]]; then
         echo "Failed to get the 'JWT' token from the useradm service."
-        echo "This is needed in order to use the demo Artifact."
+        echo "This is needed in order to upload the demo Artifact."
         echo "curl exit code: " $retval
         echo "Retrying in 5..."
     fi
@@ -233,10 +232,7 @@ do
     cout=$(curl --silent -k -X POST \
                 --fail\
                 --show-error\
-                --connect-timeout 120\
-                --retry-delay 2\
-                --retry 60 \
-                --retry-max-time 120\
+                --connect-timeout 5\
                 --header "Authorization: Bearer ${JWT}"\
                 --form "size=${ARTIFACT_SIZE_BYTES}"\
                 --form "artifact=@${DEMO_ARTIFACT_NAME}"\
