Docker Engine just got a new versioning scheme, take this into account. https://blog.docker.com/2017/03/docker-enterprise-edition/
Changelong: Support new versioning scheme of docker (e.g. 17.03.0-ce)
when validating version installed.

Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>
(cherry picked from commit ed8acbbb6a624a23e934a04aa1a1c058bc0883d8)

diff --git a/verify-docker-versions b/verify-docker-versions
--- a/verify-docker-versions
+++ b/verify-docker-versions
@@ -27,16 +27,27 @@ compare_versions() {
 
 # test Docker Engine version
 
-DOCKER_ENGINE_VERSION_REGEX_MINOR_BACKREF="Server Version: 1\.([0-9]+)\.[0-9]+"
 DOCKER_ENGINE_VERSION_STRING=$(sudo docker info 2>/dev/null | grep "Server Version")
-DOCKER_ENGINE_VERSION_MINOR=$(echo $DOCKER_ENGINE_VERSION_STRING | sed -En "s/$DOCKER_ENGINE_VERSION_REGEX_MINOR_BACKREF/\1/p")
 
-compare_versions "$DOCKER_ENGINE_VERSION_MINOR" "$VERSION_MINOR_MIN_DOCKER_ENGINE"
+DOCKER_ENGINE_VERSION_NEW_SCHEME_REGEX="Server Version: [0-9]+\.[0-9]+\.[0-9]+-[ce]e"
 
-if [ $? -ne 0 ]; then
-  echo "ERROR: Docker Engine must be on version 1.$VERSION_MINOR_MIN_DOCKER_ENGINE or larger, but found version 1.$DOCKER_ENGINE_VERSION_MINOR installed."
-  echo "DOCKER_ENGINE_VERSION_STRING=$DOCKER_ENGINE_VERSION_STRING"
-  exit 1
+if [[ $DOCKER_ENGINE_VERSION_STRING =~ $DOCKER_ENGINE_VERSION_NEW_SCHEME_REGEX ]]; then
+
+  :
+  # we support all versions in new version scheme, at least for now
+  # more info: https://blog.docker.com/2017/03/docker-enterprise-edition/
+
+else
+  DOCKER_ENGINE_VERSION_REGEX_MINOR_BACKREF="Server Version: 1\.([0-9]+)\.[0-9]+"
+  DOCKER_ENGINE_VERSION_MINOR=$(echo $DOCKER_ENGINE_VERSION_STRING | sed -En "s/$DOCKER_ENGINE_VERSION_REGEX_MINOR_BACKREF/\1/p")
+
+  compare_versions "$DOCKER_ENGINE_VERSION_MINOR" "$VERSION_MINOR_MIN_DOCKER_ENGINE"
+
+  if [ $? -ne 0 ]; then
+    echo "ERROR: Docker Engine must be on version 1.$VERSION_MINOR_MIN_DOCKER_ENGINE or larger, but found version 1.$DOCKER_ENGINE_VERSION_MINOR installed."
+    echo "DOCKER_ENGINE_VERSION_STRING=$DOCKER_ENGINE_VERSION_STRING"
+    exit 1
+  fi
 fi
 
 
