test(backend): Support running tests against Azure blob storage
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

diff --git a/backend-tests/run b/backend-tests/run
--- a/backend-tests/run
+++ b/backend-tests/run
@@ -1,28 +1,35 @@
 #!/bin/bash
 
-HERE=$(dirname $(readlink -f "$0"))
-INTEGRATION_PATH=$(dirname "$HERE")
+INTEGRATION_PATH=$(git rev-parse --show-toplevel)
 export INTEGRATION_PATH
 
 DOWNLOAD_REQUIREMENTS="true"
 
-COMPOSE_CMD_BASE="docker-compose -p backend-tests \
-        -f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml
-        "
-COMPOSE_CMD_OPEN="docker-compose -p backend-tests \
+COMPOSE_FILES_BASE="-f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml"
+COMPOSE_FILES_OPEN=" \
         -f $INTEGRATION_PATH/docker-compose.yml \
         -f $INTEGRATION_PATH/docker-compose.demo.yml \
-        -f $INTEGRATION_PATH/docker-compose.storage.minio.yml
-        -f $INTEGRATION_PATH/extra/integration-testing/docker-compose.yml
-        -f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml
+        -f $INTEGRATION_PATH/docker-compose.storage.minio.yml \
+        -f $INTEGRATION_PATH/extra/integration-testing/docker-compose.yml \
+        -f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml \
         "
-COMPOSE_CMD_ENTERPRISE="${COMPOSE_CMD_OPEN} \
+COMPOSE_FILES_ENTERPRISE="${COMPOSE_FILES_OPEN} \
         -f $INTEGRATION_PATH/docker-compose.enterprise.yml \
         -f $INTEGRATION_PATH/extra/recaptcha-testing/tenantadm-test-recaptcha-conf.yml \
         -f $INTEGRATION_PATH/extra/smtp-testing/workflows-worker-smtp-test.yml \
         -f $INTEGRATION_PATH/extra/stripe-testing/stripe-test.docker-compose.yml
         "
-COMPOSE_CMD=""
+COMPOSE_FILE_STORAGE_AZURE="-f $INTEGRATION_PATH/backend-tests/docker/docker-compose.storage.azblob.yml"
+
+COMPOSE_FILE_AZURE_SETUP="-f $INTEGRATION_PATH/backend-tests/docker/docker-compose.azblob.setup.yml"
+
+COMPOSE_FILES=""
+
+COMPOSE_UP_EXTRA_ARGS="--remove-orphans"
+
+compose_cmd() {
+    docker-compose -p backend-tests $COMPOSE_FILES $@
+}
 
 PYTEST_FILTER_OPEN="not Enterprise and not Multitenant"
 PYTEST_FILTER_ENTERPRISE="Enterprise"
@@ -35,6 +42,8 @@ PYTEST_REPORT_ENTERPRISE="--self-contained-html \
         --junit-xml=results_backend_integration_enterprise.xml \
         --html=report_backend_integration_enterprise.html"
 PYTEST_REPORT=""
+
+PYTEST_ARGS=""
 
 TOOLS="$INTEGRATION_PATH/backend-tests/downloaded-tools"
 
@@ -121,12 +130,12 @@ get_runner_requirements() {
 run_tests() {
     local RUN_ARGS="--use-aliases"
     # Need to start the backend first
-    $COMPOSE_CMD up --scale mender-backend-tests-runner=0 -d --remove-orphans
+    compose_cmd up $COMPOSE_UP_EXTRA_ARGS --scale mender-backend-tests-runner=0 -d
     if [ -n "$AZURE_IOTHUB_CONNECTIONSTRING" ]; then
         RUN_ARGS="${RUN_ARGS} -e AZURE_IOTHUB_CONNECTIONSTRING=${AZURE_IOTHUB_CONNECTIONSTRING}"
     fi
     # ... then the runner
-    $COMPOSE_CMD run $RUN_ARGS mender-backend-tests-runner
+    compose_cmd run $RUN_ARGS mender-backend-tests-runner
     return $?
 }
 
@@ -151,7 +160,7 @@ copy_test_reports_if_args() {
         shift
     done
 
-    cid=$($COMPOSE_CMD ps -aq mender-backend-tests-runner | head -n 1)
+    cid=$(compose_cmd ps -aq mender-backend-tests-runner | head -n 1)
     if [ -n "$RESULTS_FILE" ]; then
         echo "-- copying file $RESULTS_FILE"
         docker cp ${cid}:/$RESULTS_FILE . || true
@@ -163,7 +172,6 @@ copy_test_reports_if_args() {
 }
 
 prepare_pytest_args() {
-    PYTEST_ARGS=""
     filter="none"
     for val in $USER_PYTEST_ARGS; do
         if [ "$val" == "-k" ]; then
@@ -184,10 +192,17 @@ prepare_pytest_args() {
 
 cleanup(){
     if [ -z $SKIP_CLEANUP ]; then
-        $COMPOSE_CMD down -v --remove-orphans
+        compose_cmd down -v --remove-orphans
     else
         # Remove stopped container created by docker-compose run
-        $COMPOSE_CMD rm -f
+        compose_cmd rm -f
+    fi
+    if [ -n "$AZURE_STORAGE_CONTAINER_PREFIX" ]; then
+        # Remove the blob storage container if we created one
+        echo "Removing blob storage container '$AZURE_STORAGE_CONTAINER_NAME'"
+        docker-compose $COMPOSE_FILE_AZURE_SETUP run --rm \
+                       azblob-container-teardown $AZURE_STORAGE_CONTAINER_NAME
+        docker-compose $COMPOSE_FILE_AZURE_SETUP down
     fi
 }
 
@@ -203,19 +218,39 @@ script_failed=0
 for suite in "${TEST_SUITES[@]}"; do
     case "$suite" in
         open)
-            COMPOSE_CMD="$COMPOSE_CMD_OPEN"
+            COMPOSE_FILES="$COMPOSE_FILES_OPEN"
             PYTEST_FILTER="$PYTEST_FILTER_OPEN"
             PYTEST_REPORT="$PYTEST_REPORT_OPEN"
             ;;
         enterprise)
-            COMPOSE_CMD="$COMPOSE_CMD_ENTERPRISE"
+            COMPOSE_FILES="$COMPOSE_FILES_ENTERPRISE"
             PYTEST_FILTER="$PYTEST_FILTER_ENTERPRISE"
             PYTEST_REPORT="$PYTEST_REPORT_ENTERPRISE"
             ;;
     esac
 
+    # Are we running in Azure mode?
+    if [ -n "$AZURE_STORAGE_CONTAINER_PREFIX" ]; then
+        # Create a container (bucket) will be removed in cleanup
+        rand_suffix=$(cat /dev/urandom | tr -dc 'a-z' | head -c 8)
+        date_suffix=$(date '+%Y%m%d-%H%M%S')
+        container="${AZURE_STORAGE_CONTAINER_PREFIX}-${date_suffix}-${rand_suffix}"
+        export AZURE_STORAGE_CONTAINER_NAME="${container}"
+        echo "Creating container '$AZURE_STORAGE_CONTAINER_NAME'"
+        docker-compose $COMPOSE_FILE_AZURE_SETUP run --rm \
+                       azblob-container-setup $AZURE_STORAGE_CONTAINER_NAME
+        ec=$?
+        if [ $ec -ne 0 ]; then
+            echo -n 'Failed to setup blob storage for testing'
+            exit $ec
+        fi
+    fi
     if [ -n "$K8S" ]; then
-        COMPOSE_CMD="${COMPOSE_CMD_BASE}"
+        COMPOSE_FILES="${COMPOSE_FILES_BASE}"
+    elif [ -n "$AZURE_STORAGE_CONTAINER_NAME" ]; then
+        COMPOSE_FILES="${COMPOSE_FILES} ${COMPOSE_FILE_STORAGE_AZURE}"
+        COMPOSE_UP_EXTRA_ARGS="${COMPOSE_UP_EXTRA_ARGS} --scale minio=0"
+        PYTEST_ARGS="$PYTEST_ARGS -m storage_test"
     fi
 
     prepare_pytest_args
@@ -228,7 +263,7 @@ for suite in "${TEST_SUITES[@]}"; do
     if [ $run_tests_retcode -ne 0 ]; then
         tmppath=$(mktemp ${HERE}/acceptance.XXXXXX)
         echo "-- tests failed, dumping logs to $tmppath"
-        $COMPOSE_CMD logs > $tmppath
+        compose_cmd logs > $tmppath
     fi
 
     copy_test_reports_if_args $PYTEST_REPORT
